services:
  blossomtune-server-node:
    build: .
    image: docker.io/ethicalabs/blossomtune-llm:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  blossomtune-client-node-01:
    build: .
    image: docker.io/ethicalabs/blossomtune-llm:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      SUPERLINK: "blossomtune-server-node:9092"
      NODE_DATA_PATH: "/app/data/"
      PARTITION_ID: 0
      NUM_PARTITIONS: 10
    volumes:
      - ./data:/app/data
    command: ["supernode"]
  blossomtune-client-node-02:
    build: .
    image: docker.io/ethicalabs/blossomtune-llm:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      SUPERLINK: "blossomtune-server-node:9092"
      NODE_DATA_PATH: "/app/data/"
      PARTITION_ID: 1
      NUM_PARTITIONS: 10
    volumes:
      - ./data:/app/data
    command: ["supernode"]
  blossomtune-client-node-03:
    build: .
    image: docker.io/ethicalabs/blossomtune-llm:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      SUPERLINK: "blossomtune-server-node:9092"
      NODE_DATA_PATH: "/app/data/"
      PARTITION_ID: 2
      NUM_PARTITIONS: 10
    volumes:
      - ./data:/app/data
    command: ["supernode"]
  blossomtune-client-node-04:
    build: .
    image: docker.io/ethicalabs/blossomtune-llm:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      SUPERLINK: "blossomtune-server-node:9092"
      NODE_DATA_PATH: "/app/data/"
      PARTITION_ID: 3
      NUM_PARTITIONS: 10
    volumes:
      - ./data:/app/data
    command: ["supernode"]
  blossomtune-client-node-05:
    build: .
    image: docker.io/ethicalabs/blossomtune-llm:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      SUPERLINK: "blossomtune-server-node:9092"
      NODE_DATA_PATH: "/app/data/"
      PARTITION_ID: 4
      NUM_PARTITIONS: 10
    volumes:
      - ./data:/app/data
    command: ["supernode"]
  blossomtune-client-node-06:
    build: .
    image: docker.io/ethicalabs/blossomtune-llm:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      SUPERLINK: "blossomtune-server-node:9092"
      NODE_DATA_PATH: "/app/data/"
      PARTITION_ID: 5
      NUM_PARTITIONS: 10
    volumes:
      - ./data:/app/data
    command: ["supernode"]
