services:
  blossomtune-server-node:
    build: .
    environment:
      NODE_SAVE_PATH: "/app/results/"
    volumes:
      - ./results:/app/results
  blossomtune-client-node:
    build: .
    environment:
      SUPERLINK: "blossomtune-server-node:443"
      NODE_DATA_PATH: "/app/data/"
    volumes:
      - ./data:/app/data
