services:
  blossomtune-server-node:
    build: .
    volumes:
      - ./results:/app/results
    command: ["superlink"]
  blossomtune-client-node-01:
    build: .
    environment:
      SUPERLINK: "blossomtune-server-node:9093"
      NODE_DATA_PATH: "/app/data/"
      PARTITION_ID: 0
      NUM_PARTITIONS: 10
    volumes:
      - ./data:/app/data
    command: ["supernode"]
  blossomtune-client-node-02:
    build: .
    environment:
      SUPERLINK: "blossomtune-server-node:9093"
      NODE_DATA_PATH: "/app/data/"
      PARTITION_ID: 1
      NUM_PARTITIONS: 10
    volumes:
      - ./data:/app/data
    command: ["supernode"]
  blossomtune-client-node-03:
    build: .
    environment:
      SUPERLINK: "blossomtune-server-node:9093"
      NODE_DATA_PATH: "/app/data/"
      PARTITION_ID: 2
      NUM_PARTITIONS: 10
    volumes:
      - ./data:/app/data
    command: ["supernode"]
  blossomtune-client-node-04:
    build: .
    environment:
      SUPERLINK: "blossomtune-server-node:9093"
      NODE_DATA_PATH: "/app/data/"
      PARTITION_ID: 3
      NUM_PARTITIONS: 10
    volumes:
      - ./data:/app/data
    command: ["supernode"]
